DAWEY/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DAWEY.views import HomePageView, HomePageView_Seminario_User, HomePageView_User, HomePageView_Corso_User, \
    HomePageView_Competizione_User, HomePageView_Sportivo_User

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('home', HomePageView_User.as_view(), name='home_user'),
    path('home/seminario', HomePageView_Seminario_User.as_view(), name='home_user_seminario'),
    path('home/corso', HomePageView_Corso_User.as_view(), name='home_user_corso'),
    path('home/competizione', HomePageView_Competizione_User.as_view(), name='home_user_competizione'),
    path('home/sportivo', HomePageView_Sportivo_User.as_view(), name='home_user_sportivo'),
    path('user_management/', include('user_management.urls')),
    path('eventi_management/', include('eventi_management.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.urls import path, reverse_lazy
from user_management import views
from django.contrib.auth import views as auth_views

app_name = 'user_management'

urlpatterns = [
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/reset_password_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_password_confirm.html",
                                                     success_url=reverse_lazy('user_management:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_complete.html'),
         name='password_reset_complete'),
    path("password_reset", views.password_reset_request, name="password_reset"),

    path('registration', views.CreateUserView.as_view(), name='user-register'),
    path('login', views.LoginUserView.as_view(), name='user-login'),
    path('logout', views.LogoutUserView.as_view(), name='user-logout'),
    path('profile', views.ProfileView.as_view(), name='user'),
    path('profile/update', views.UpdateUserView.as_view(), name='user-update'),
    path('update-user-responsabile', views.update_user_responsabile, name='user-update-ajax'),
    path('profile/delete', views.DeleteUserView.as_view(), name='delete-user'),
]

user_management/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    """
    Registration form where the user entering: username, email, name, last name
    and password can create a new profile to access the application
    """
    username = forms.CharField(max_length=50, label='Username',
                               widget=forms.TextInput(attrs={'placeholder': 'Es: mario.rossi'}))
    first_name = forms.CharField(max_length=50, label='Nome',
                                 widget=forms.TextInput(attrs={'placeholder': 'Es: Mario'}))
    last_name = forms.CharField(max_length=50, label='Cognome',
                                widget=forms.TextInput(attrs={'placeholder': 'Es: Rossi'}))
    email = forms.EmailField(label='Email')

    helper = FormHelper()
    helper.form_id = 'utente-crispy-form'
    helper.form_method = 'POST'

    error_messages = {
        'password_mismatch': "Le password non corrispondono!",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # set style-input class for the dark-theme
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'style-input'

        self.helper.layout = Layout(
            Row(
                Column('username', css_class='form-group mb-0'),
                Column('first_name', css_class='form-group mb-0'),
                Column('last_name', css_class='form-group mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('email', css_class='form-group mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password1', css_class='form-group col-md-6 mb-0'),
                Column('password2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
        )

    class Meta:
        model = User
        fields = ("email", "username", "first_name", "last_name",)

    def clean_username(self):
        """
        Cheks if the inserted username is already present in the database (only if it's been changed from the original).
        :returns: username
        :raises: forms.ValidationError
        """
        username = self.cleaned_data.get('username')

        if User.objects.filter(username=username).count():
            raise forms.ValidationError(
                'Un utente con questo username è già presente.')
        return username

    def clean_email(self):
        """
        Cheks if the inserted mail is already present in the database (only if it's been changed from the original).
        :returns: mail
        :raises: forms.ValidationError
        """
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).count():
            raise forms.ValidationError(
                'Un utente con questa mail è già presente.')
        return email


class LoginForm(AuthenticationForm):
    """
    Login form where an already registered user can enter the username and password to authenticate
    """
    helper = FormHelper()
    helper.form_id = 'utente-login-crispy-form'
    helper.form_method = 'POST'

    error_messages = {
        'invalid_login': "Username o password errati. Perfavore, controlla i tuoi dati.",
        'inactive': "Questo account non è più attivo.",
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None

        super().__init__(*args, **kwargs)

        self.fields['username'].label = "Nome utente/email"

        # set style-input class for the dark-theme
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'style-input'

        self.helper.layout = Layout(
            Row(
                Column('username', css_class='form-group mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password', css_class='form-group mb-0'),
                css_class='form-row'
            ),
        )


class UpdateUserForm(forms.Form):
    """
    Form for updating the user data.
    Not inheritance of ModelForm because otherwise it wouldn't be possible to update the user data because the username
    is already present in the database.
    """
    username = forms.CharField(required=True, label='Username')
    email = forms.EmailField(required=True, label='Email')
    first_name = forms.CharField(required=True, label='Nome')
    last_name = forms.CharField(required=True, label='Cognome')

    helper = FormHelper()
    helper.form_id = 'update-user-crispy-form'
    helper.form_method = 'POST'
    helper.add_input(Submit(
        'cancel',
        'Annulla',
        css_class='btn-secondary',
        formnovalidate='formnovalidate',
    ))
    helper.add_input(Submit(
        'submit',
        'Salva',
        css_class='btn btn-success',
    ))

    # class Meta:
    #     fields = ('username', 'email', 'first_name', 'last_name')
    #     labels = {
    #         'username': 'Username',
    #         'email': 'Email',
    #         'first_name': 'Nome',
    #         'last_name': 'Cognome',
    #     }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # set style-input class for the dark-theme
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'style-input'

    def clean_username(self):
        """
        Checks if the inserted username is already present in the database (only if it's been changed from the original)
        :returns: username
        :raises: forms.ValidationError
        """
        username = self.cleaned_data.get('username')

        if username != self.files.username and User.objects.filter(username=username).count():
            raise forms.ValidationError(
                'Un utente con questo username è già presente.')
        return username

    def clean_email(self):
        """
        Checks if the inserted mail is already present in the database (only if it's been changed from the original).
        :returns: mail
        :raises: forms.ValidationError
        """
        email = self.cleaned_data.get('email')

        if email != self.files.email and User.objects.filter(email=email).count():
            raise forms.ValidationError(
                'Un utente con questa mail è già presente.')
        return email

    def save(self, commit=True):
        """
        Updates the authenticated user data on the database.
        :param commit: If save the new data.
        :returns: authenticated user.
        """
        # Accessing the authenticated user passed from the View in "files".
        current_user = self.files
        current_user.username = self.cleaned_data['username']
        current_user.email = self.cleaned_data['email']
        current_user.first_name = self.cleaned_data['first_name']
        current_user.last_name = self.cleaned_data['last_name']

        if commit:
            current_user.save()

        return current_user

user_management/views.py
from datetime import date
from itertools import chain

from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, TemplateView, FormView

from DAWEY.views import BasicView
from eventi_management.models import Seminario, Competizione, Sportivo, Corso
from user_management.forms import RegistrationForm, LoginForm, UpdateUserForm
from user_management.models import UserAndEvent


class CreateUserView(CreateView):
    """
    View with registration form
    """
    form_class = RegistrationForm
    template_name = 'registration/registration_form.html'
    success_url = reverse_lazy('user_management:user-login')


class LoginUserView(LoginView):
    """
    View with login form
    """
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('home')


class PasswordResetUserView(PasswordResetView):
    """
    View with login form
    """
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('home')


class LogoutUserView(LogoutView):
    """
    View for logging out
    """
    template_name = 'registration/logged_out.html'
    success_url = reverse_lazy('user_management:user-login')


class ProfileView(BasicView, TemplateView, LoginRequiredMixin):
    """
    View for displaying the account of the authenticated user.
    """
    template_name = 'user_profile/user_profile.html'
    user_for_profile = None
    events = None
    seminario = None
    corso = None
    competizione = None
    sportivo = None

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        try:
            self.user_for_profile = get_object_or_404(User, pk=self.request.user.pk)

            id_eventi_prenotati = UserAndEvent.objects.filter(user=self.request.user.pk).values('id_event')
            self.seminario = Seminario.objects.filter(date_start__lte=date.today(), pk__in=id_eventi_prenotati)
            self.corso = Corso.objects.filter(date_start__lte=date.today(), pk__in=id_eventi_prenotati)
            self.competizione = Competizione.objects.filter(date_start__lte=date.today(), pk__in=id_eventi_prenotati)
            self.sportivo = Sportivo.objects.filter(date_start__lte=date.today(), pk__in=id_eventi_prenotati)
            self.events = list(chain(self.seminario, self.corso, self.competizione, self.sportivo))
        except ObjectDoesNotExist:
            raise Http404

        return context


class UpdateUserView(BasicView, FormView, LoginRequiredMixin):
    """
    View for updating the data of the authenticated user account.
    """
    template_name = 'user_profile/user_update.html'
    success_url = reverse_lazy('user_management:user')

    def post(self, request, *args, **kwargs):
        # Sends the authenticated user to the form in order to update it.
        form = UpdateUserForm(request.POST, request.user)
        # Click on "Cancel" button
        if "cancel" in request.POST:
            return HttpResponseRedirect(reverse_lazy('user_management:user'))
        # Click on "Submit" button
        else:
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse_lazy('user_management:user'))

            context = ({'view': self,
                        'form': form,
                        })
            return super(UpdateUserView, self).render_to_response(context)

    def get(self, request, *args, **kwargs):
        # Populates the form with the authenticated user data.
        form = UpdateUserForm(initial={
            'username': request.user.username,
            'email': request.user.email,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        })
        context = ({'view': self,
                    'form': form,
                    })
        return super(UpdateUserView, self).render_to_response(context)


class DeleteUserView(LoginRequiredMixin, View):
    """
    View for deleting the account of the authenticated user.
    Redirects to :view: LoginUserView
    """

    def get(self, request):
        User.objects.get(pk=request.user.pk).delete()
        return HttpResponseRedirect(reverse_lazy('user_management:user-login'))

    def post(self):
        User.objects.get(pk=self.request.user.pk).delete()
        return HttpResponseRedirect(reverse_lazy('user_management:user-login'))


@login_required
@require_POST
@csrf_protect
def update_user_responsabile(request):
    if request.method == "POST":
        utente = request.user
        if utente.user_settings.is_prof:
            utente.user_settings.is_prof = False
        else:
            utente.user_settings.is_prof = True

        utente.user_settings.save()
        data = {
            'Aggiornato': True
        }
        return JsonResponse(data)


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'incerti.marco1997@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("user_management:password_reset_done")

            else:
                messages.error(request, 'Non esistono utenti con questa email.')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="registration/reset_password.html",
                  context={"password_reset_form": password_reset_form})

user_management/templates/user_profile/base_user_profile.html
{% comment %}
Base template used to show user data (account).
{% endcomment %}
{% load static %}

<div class="container mt-5">
    <div class="box p-3 shadow">
        <div class="p-3" style="text-align: center">
            <h3 class="font-weight-bold">{{ title_profile }}</h3>
        </div>
        <div class="card-columns mt-3">
            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">USERNAME</h6>
                    <p class="card-text font-weight-bold">{{ user_for_profile.username }}</p>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">NOME</h6>
                    <p class="card-text font-weight-bold">{{ user_for_profile.first_name }} {{ user_for_profile.last_name }}</p>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">EMAIL</h6>
                    <p class="card-text font-weight-bold">{{ user_for_profile.email }}</p>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">DATA DI ISCRIZIONE</h6>
                    <div class="container">
                        <span class="card-text font-weight-bold">{{ user_for_profile.date_joined|date:'l' }}</span><br>
                        <span class="card-text font-weight-bold">{{ user_for_profile.date_joined|date:'d/m/Y' }}</span>
                    </div>
                </div>
            </div>

            <div class="card flip-card text-center">
                <div class="flip-card-inner  p-2">
                    <div class="flip-card-front">
                        <!-- Content -->
                        <div class="card-body">
                            <h6 class="card-title">PUOI PUBBLICARE?</h6>
                            <div class="container">
                                {% if  user.user_settings.is_prof %}
                                    <span class="card-text font-weight-bold">SI</span>
                                {% else %}
                                    <span class="card-text font-weight-bold">NO</span><br>
                                    <span class="card-text">Richiedi il permesso</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                <div class="flip-card-back">
                    {% if user.user_settings.is_prof %}
                        <h4>Vuoi smettere di pubblicare?</h4>
                            <button id="responsabile-button2" type="button" class="btn btn-danger m-3">SI, voglio
                                smettere di pubblicare</button>
                    {% else %}
                            <h4>Vuoi pubblicare?</h4>
                            <button id="responsabile-button" type="button" class="btn btn-warning m-3">SI, voglio
                                pubblicare
                            </button>
                    {% endif %}
                        </div>

                </div>
            </div>

            {% if user_for_profile == user %}
                <a class="card bg-info text-white text-center" href="{% url 'user_management:user-logout' %}">
                    <div class="card-body">
                        <h5 class="card-text">Esci</h5>
                    </div>
                </a>

                <a class="card bg-warning text-white text-center" href="{% url 'user_management:user-update' %}">
                    <div class="card-body">
                        <h5 class="card-text">Modifica account</h5>
                    </div>
                </a>

                <a class="card bg-danger text-white text-center trigger-btn" id="card-delete-user" href="#myModal"
                   data-toggle="modal">
                    <div class="card-body">
                        <h5 class="card-text">Elimina account</h5>
                    </div>
                </a>
            {% endif %}
        </div>
    </div>
</div>

{% if user_for_profile == user %}
    <!-- Modal HTML for deleting user account-->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminare questo account?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Questa azione non sarà reversibile. Oltre all'account verranno cancellate anche tutte le
                        analisi
                        di
                        testi salvate.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                    <a id="delete-user-button" type="button" class="btn btn-danger"
                       href="{% url 'user_management:delete-user' %}">Elimina</a>
                </div>
            </div>
        </div>
    </div>

{% endif %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}
{% block extra_javascript %}
    {% include 'user_profile/usere_ajax.html' %}
{% endblock %}

user_management/templates/user_profile/user_profile.html
{% extends 'base.html' %}
{% load app_filters %}
{% load static %}

{% comment %}
Template used to show the authenticated user data (account).
Includes the base_user_profile template.
{% endcomment %}

{% block title %}Profilo{% endblock %}

{% block content %}
    {% include 'user_profile/base_user_profile.html' with user_for_profile=view.user_for_profile title_profile='Il mio profilo:' %}
    <div class="row">
        <div class="content_2 container-md shadow p-3 mt-2 bg-white mt-1">
            <div class="ml-3 d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-start">
                    <h2 class="mr-2 font-weight-light">Gli eventi a cui ho partecipato</h2>
                </div>
            </div>
            <hr>
            <ul class="nav nav-pills nav-fill p-2 " id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-tutti-tab" data-toggle="pill" href="#pills-tutti" role="tab"
                       aria-controls="pills-tutti" aria-selected="true">Tutti</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-seminari-tab" data-toggle="pill" href="#pills-seminari" role="tab"
                       aria-controls="pills-seminari" aria-selected="false">Seminari</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-corsi-tab" data-toggle="pill" href="#pills-corsi" role="tab"
                       aria-controls="pills-corsi" aria-selected="false">Corsi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-competizioni-tab" data-toggle="pill" href="#pills-competizioni"
                       role="tab"
                       aria-controls="pills-competizioni" aria-selected="false">Competizioni</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-sportivi-tab" data-toggle="pill" href="#pills-sportivi" role="tab"
                       aria-controls="pills-sportivi" aria-selected="false">Sportivi</a>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-tutti" role="tabpanel"
                     aria-labelledby="pills-tutti-tab">
                    {% include 'user_profile/base/list_object_eventi_utente.html' with object_list=view.events %}
                </div>
                <div class="tab-pane fade" id="pills-seminari" role="tabpanel" aria-labelledby="pills-seminari-tab">
                    {% include 'user_profile/base/list_object_eventi_utente.html' with object_list=view.seminario %}
                </div>
                <div class="tab-pane fade" id="pills-corsi" role="tabpanel" aria-labelledby="pills-corsi-tab">
                    {% include 'user_profile/base/list_object_eventi_utente.html' with object_list=view.corso %}
                </div>
                <div class="tab-pane fade" id="pills-competizioni" role="tabpanel"
                     aria-labelledby="pills-competizioni-tab">
                    {% include 'user_profile/base/list_object_eventi_utente.html' with object_list=view.competizioni %}
                </div>
                <div class="tab-pane fade" id="pills-sportivi" role="tabpanel" aria-labelledby="pills-sportivi-tab">
                    {% include 'user_profile/base/list_object_eventi_utente.html' with object_list=view.sportivo %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/eventi_creati_utente.css' %}">
{% endblock %}

user_management/templates/user_profile/user_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Aggiorna il tuo account{% endblock %}

{% block content %}
    <div class="box-width-radius container-md shadow p-4 mt-5 bg-white w-auto">
        <h2 class="font-weight-bold">Aggiorna il tuo account</h2>
        <hr>
        {% crispy form %}
    </div>
{% endblock %}

user_management/templates/user_profile/usere_ajax.html
<script>
    $("#responsabile-button").click(function () {

        $.ajax({
            type: 'POST',
            headers: {
                "X-CSRFToken": '{{ csrf_token }}'
            },
            url: "{% url 'user_management:user-update-ajax' %}",
            data: {
                'responsabile': true,
            },
            dataType: 'json',
            beforeSend: function () {
                $.blockUI({});
            },
            complete: function () {
                $.unblockUI();
            },

            success: function () {
                Swal.fire({
                    title: 'Sei diventato un resposabile',
                    text: 'Ora puoi pubblicare i tuoi eventi',
                    icon: 'success',
                    confirmButtonText: 'Ok',
                }).then((result) => {
                    // Reload the Page
                    location.reload();
                });
            }
        });
    });

    $("#responsabile-button2").click(function () {
        let button = $(this);
        $.ajax({
            type: 'POST',
            headers: {
                "X-CSRFToken": '{{ csrf_token }}'
            },
            url: "{% url 'user_management:user-update-ajax' %}",
            data: {
                'responsabile': false,
            },
            dataType: 'json',
            beforeSend: function () {
                $.blockUI({});
            },
            complete: function () {
                $.unblockUI();
            },
            success: function () {
                Swal.fire({
                    title: 'Non sei più un resposabile',
                    text: 'Non puoi più pubblicare i tuoi eventi',
                    icon: 'success',
                    confirmButtonText: 'Ok'
                }).then((result) => {
                    // Reload the Page
                    location.reload();
                });
            }
        });
    });
</script>