DAWEY/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DAWEY.views import HomePageView, HomePageView_Seminario_User, HomePageView_User, HomePageView_Corso_User, \
    HomePageView_Competizione_User, HomePageView_Sportivo_User

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('home', HomePageView_User.as_view(), name='home_user'),
    path('home/seminario', HomePageView_Seminario_User.as_view(), name='home_user_seminario'),
    path('home/corso', HomePageView_Corso_User.as_view(), name='home_user_corso'),
    path('home/competizione', HomePageView_Competizione_User.as_view(), name='home_user_competizione'),
    path('home/sportivo', HomePageView_Sportivo_User.as_view(), name='home_user_sportivo'),
    path('user_management/', include('user_management.urls')),
    path('eventi_management/', include('eventi_management.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventi_management/urls.py
from django.urls import path

from eventi_management import views

app_name = 'eventi_management'

urlpatterns = [
    path('event/insert', views.InsertEvent.as_view(), name='event-insert'),
    path('event/insert/seminario', views.SeminarioInsert.as_view(), name='seminario-insert'),
    path('event/insert/competizione', views.CompetizioneEvent.as_view(), name='competizione-insert'),
    path('event/insert/corso', views.CorsoInsert.as_view(), name='corso-insert'),
    path('event/insert/sportivo', views.SportivoInsert.as_view(), name='sportivo-insert'),
    path('event/list', views.EventListUserCreate.as_view(), name='event-list'),
    path('event/<int:pk>', views.EventoSingolo.as_view(), name='evento-singolo'),
    path('event/user_event', views.event_user, name='event-user'),
    path('event/<int:pk>/delete', views.DeleteEvent.as_view(), name='event-delete'),
    path('event/user_delete_event', views.elimina_evento_user, name='event-delete-user'),
    path('event/<int:pk>/delete_user_evento', views.DeleteUserFromEvent.as_view(), name='event-delete-user-evento'),
    path('event/<int:pk>/seminario/update', views.SeminarioUpdate.as_view(), name='seminario-update'),
    path('event/<int:pk>/corso/update', views.CorsoUpdate.as_view(), name='corso-update'),
    path('event/<int:pk>/competizione/update', views.CompetizioneUpdate.as_view(), name='competizione-update'),
    path('event/<int:pk>/sportivo/update', views.SportivoUpdate.as_view(), name='sportivo-update'),
    path('event/<int:pk>/list_user', views.PartecipantiEvento.as_view(), name='event-list'),
]

user_management/urls.py
from django.urls import path, reverse_lazy
from user_management import views
from django.contrib.auth import views as auth_views

app_name = 'user_management'

urlpatterns = [
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/reset_password_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_password_confirm.html",
                                                     success_url=reverse_lazy('user_management:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_complete.html'),
         name='password_reset_complete'),
    path("password_reset", views.password_reset_request, name="password_reset"),

    path('registration', views.CreateUserView.as_view(), name='user-register'),
    path('login', views.LoginUserView.as_view(), name='user-login'),
    path('logout', views.LogoutUserView.as_view(), name='user-logout'),
    path('profile', views.ProfileView.as_view(), name='user'),
    path('profile/update', views.UpdateUserView.as_view(), name='user-update'),
    path('update-user-responsabile', views.update_user_responsabile, name='user-update-ajax'),
    path('profile/delete', views.DeleteUserView.as_view(), name='delete-user'),
]

templates/base.html
{% comment %}
Base template of the application.
{% endcomment %}

{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Google index -->
    <meta name="google-site-verification" content="xYd-zlMcEnfOUGYZFrCNzQv1ZUTLPmKZtWdES2tLawI"/>

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/v4-shims.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,500;0,700;1,900&display=swap"
          rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/css/bootstrap-select.min.css"
          integrity="sha256-jwJEU4p1YdtymLFwAjYfam5Pj5NOnylms63k7LYQ9Jk=" crossorigin="anonymous"/>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
          integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous"/>

    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <link rel="stylesheet"
          href="{% static 'css/style.css' %}">
    <link rel="stylesheet"
          href="{% static 'css/responsive_style.css' %}">
    {% block extra_css %} {% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>

<body data-spy="scroll" data-target=".fixed-top">

<!-- Preloader -->
<div class="spinner-wrapper">
    <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
    </div>
</div>
<!-- end of preloader -->

{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<!-- Moment.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
        integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA="
        crossorigin="anonymous"></script>
<!-- Tempus Dominus Bootstrap 4 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
        integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4="
        crossorigin="anonymous"></script>


<!-- Optional JavaScript -->
<script src="{% static 'js/jquery_blockUI_script.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script> <!-- Custom scripts -->
{% block extra_javascript %}{% endblock %}
</body>
</html>

templates/evento_singolo.html
{% extends 'base.html' %}
{% load app_filters %}
{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}
    {% include 'base/header.html'  %}
    <div class="container-fluid">
        <div class="row flex-xl-nowrap">
            <div class="col col-big ">
                <div class="content">
                    <div class="content mt-3 p-3 shadow">
                        <div class="container-fluid">
                            <div class="row">
                                {% if view.evento.foto %}
                                    <div class="content">
                                        <img src="{{ view.evento.foto.url }}" alt="..." class="img-thumbnail"
                                             style="height: 200px">
                                    </div>
                                {% endif %}
                                <div class="col">
                                    <div>
                                        <h1 style="font-weight: bold;">{{ view.evento.title }}</h1>
                                    </div>
                                    <div class="d-inline-flex p-3"
                                         style="border-radius: 15px; background-color: #d8a8ff ">
                                        <h4>
                                            Data: {{ view.evento.date|date:"d F Y" }}<br>Orario: {{ view.evento.date|time:"H:i" }}
                                        </h4>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div>
                                <h4>Descrizione</h4>
                            </div>
                            <div>
                                <p>{{ view.evento.descrizione }}</p>
                            </div>
                            <br>
                            {% if view.evento.ospite %}
                                <div>
                                    <p>Con la partecipazione di: <span
                                            style="font-weight: bold; font-size: larger">{{ view.evento.ospite }}</span>
                                    </p>
                                </div>
                            {% endif %}
                            {% if view.evento.luogo %}
                                <div>
                                    <p>L'evento si terrà: <span
                                            style="font-weight: bold; font-size: larger"> {{ view.evento.luogo }}</span>
                                    </p>
                                </div>
                            {% endif %}
                            <div>
                                <p>Recapiti organizzatore: <span
                                        style="font-weight: bold; font-size: larger"> {{ view.creatore }}</span><br>
                                    Indirizzo email: <span
                                            style="font-weight: bold; font-size: larger"><a
                                            href="mailto:{{ view.creatore.email }}">{{ view.creatore.email }}</a></span>
                                </p>
                                {% if view.evento.email_extra %}
                                    <p>Email aggiuntiva per informazioni: <a
                                            href="mailto:{{ view.evento.email_extra }}">{{ view.evento.email_extra }}</a>
                                    </p>
                                {% endif %}
                                {% if view.evento.corso %}
                                    <p>Prezzo: {{ view.evento.corso.prezzo }} € <br>
                                        Responsabile: {{ view.evento.corso.responsabile }}
                                    </p>
                                {% endif %}
                                {% if view.evento.competizione %}
                                    <p>Sponsor: {{ view.evento.competizione.sponsor }} € <br>
                                        Responsabile: {{ view.evento.competizione.responsabile }} <br>
                                        Numero di persone per
                                        squadra: {{ view.evento.competizione.n_persone_per_squadra }} <br>
                                        Premio: {{ view.evento.competizione.premio }} €
                                    </p>
                                {% endif %}
                                {% if view.evento.sportivo %}
                                    <p>Sport: {{ view.evento.sportivo.sport }} € <br>
                                        Responsabile: {{ view.evento.sportivo.responsabile }}
                                    </p>
                                {% endif %}
                                {% if view.evento.link %}
                                    <p>Link evento: <a href="{{ view.evento.link }}">{{ view.evento.link }}</a>
                                    </p>
                                {% endif %}
                            </div>
                            <div class="d-flex flex-row">
                                {% if view.evento.posti %}
                                    <div class="d-inline-flex p-3 mr-3"
                                         style="border-radius: 15px; background-color: #a5dc86 ">
                                        <h5>
                                            Posti ancora disponibili: {{ view.evento | get_differenze_n_partecipanti }}
                                            su {{ view.evento.posti }}
                                        </h5>
                                    </div>
                                {% endif %}
                                <div class="d-inline-flex mr-3 p-3"
                                     style="border-radius: 15px; background-color: #facea8 ">
                                    <h5>{{ view.evento.category.name }}</h5>
                                </div>
                            </div>
                        {% if user.is_authenticated %}
                            {% if view.evento in view.object_eventi_prenotati %}
                                <div class="d-flex justify-content-end mt-2">
                                    <button id="button-eliminati" type="button" class="btn btn-danger btn-lg">Voglio
                                        togliere la mia prenotazione
                                    </button>
                                </div>
                            {% else %}
                                <div class="d-flex justify-content-end mt-2">
                                    <button id="button-prenotati" type="button" class="btn btn-success btn-lg">Mi
                                        prenoto
                                    </button>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                    </div>
                </div>
            </div>
            {% if view.object_eventi_prenotati %}
                {% include 'base/nav_eventi_prenotati.html' with object_list=view.object_eventi_prenotati%}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/homepage_user.css' %}">
{% endblock %}

{% block extra_javascript %}
    <script src="{% static  'js/morphext.min.js' %}"></script> <!-- Morphtext rotating text in the header -->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script>
        $(function () {
            /** event on click of save analysis button */
            $('#button-prenotati').click(function () {
                let button = $(this);
                var user = {{ user.id|safe}};
                var evento = {{ view.evento.id|safe}};
                ajaxUserAndEvento(user, evento, button);
            });
        });
    </script>
    <script>
        $(function () {
            /** event on click of save analysis button */
            $('#button-eliminati').click(function () {
                let button = $(this);
                var user_id = {{ user.id }};
                var evento_id = {{ view.evento.id }};
                ajaxDeleteUserAndEvento(user_id, evento_id, button);
            });
        });
    </script>
    {% include 'UserAndEvent_ajax.html' %}
    {% include 'eliminaEventoUserAjax.html' %}
{% endblock %}

templates/footer.html
{% load static %}


<!-- Static footer -->
<footer class="page-footer font-small text-center pt-4">

  <!-- Copyright -->
  <div class="footer-copyright text-center">© 2020 Copyright:
    <a class="style-link" href="https://gitlab.com/marco_incerti/tecnologie_web"> DAWEY</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/homepage_user.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% block title %}Homepage{% endblock %}

{% block content %}
{% include 'base/header.html'  %}
    <div class="container-fluid">
        <div class="row flex-xl-nowrap">
            <div class="col col-big ">
                {% if view.object_list %}
                    <div class="content_2 p-3 mt-3 shadow">
                        <h1 class="font-weight-bold">Gli eventi programmati:</h1>
                    </div>
                    <div class="card-columns mt-3 pr-4 ">
                        {% for e in view.object_list %}
                            <div class="card m-3 shadow" style="border-radius: 30px">
                                {% if e.foto %}
                                    <img src="{{ e.foto.url }}" class="card-img-top center p-3" alt="...">
                                {% endif %}
                                <div class="card-body">
                                    <div class="d-flex p-3" style="border-radius: 15px; background-color: #ffcb86">
                                        <h5 class="card-title" style="font-weight: bold;">{{ e.title }}</h5>
                                    </div>
                                    <div class="d-inline-flex mt-2 pr-3 pl-3"
                                         style="border-radius: 15px; background-color: #d8a8ff ">
                                        <h7 class="card-title mt-2">{{ e.date|date:"d F Y" }}<br>
                                            ORARIO: {{ e.date|time:"H:i" }}</h7>
                                    </div>
                                    {% if e.posti %}
                                        <div class="d-inline-flex mt-2 p-2"
                                             style="border-radius: 15px; background-color: #a5dc86 ">
                                            <h7>Posti occupati:</h7>
                                            <span style="font-weight: bold;">{{ e.pk | get_n_partecipanti }} su {{ e.posti }}</span>
                                        </div>
                                    {% endif %}
                                    <hr>
                                    {% if e.ospite %}
                                        <p class="card-text" style="font-weight: bold;">Ospite: {{ e.ospite }}</p>
                                        <hr>
                                    {% endif %}
                                    <p class="card-text">{{ e.descrizione|truncatechars:200 }}</p>
                                    <hr>
                                    <div class="d-flex justify-content-end">
                                        <a class="btn btn-info w-auto mt-2 mr-2"
                                           href="{% url 'eventi_management:evento-singolo' e.pk %}" role="button">Leggi
                                            di più...</a>
                                    </div>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% else %}
                        <div class="d-flex justify-content-center m-4" style="font-size: 30px" >Non ci sono eventi disponibili</div>
                {% endif %}

            </div>
        {% if view.object_eventi_prenotati %}
            {% include 'base/nav_eventi_prenotati.html' with object_list=view.object_eventi_prenotati%}
        {% endif %}
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/homepage_user.css' %}">
{% endblock %}

{% block extra_javascript %}
    <script src="{% static  'js/morphext.min.js' %}"></script> <!-- Morphtext rotating text in the header -->
    <script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

templates/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-md navbar-dark navbar-custom fixed-top">
    <!-- Text Logo - Use this if you don't have a graphic logo -->
    <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Aria</a> -->

    <a href="{% url 'home' %}">
        <span class="navbar-brand mb-0 h1 ">Dawey</span>
    </a>
    <!-- Mobile Menu Toggle Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-awesome fas fa-bars"></span>
        <span class="navbar-toggler-awesome fas fa-times"></span>
    </button>
    <!-- end of mobile menu toggle button -->

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link m-1 page-scroll" href="{% url 'home_user' %}">HOME <span
                        class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link m-1 page-scroll" href="{% url 'home_user_seminario' %}">SEMINARI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link m-1 page-scroll" href="{% url 'home_user_corso' %}">CORSI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link m-1 page-scroll" href="{% url 'home_user_competizione' %}">COMPETIZIONI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link m-1 page-scroll" href="{% url 'home_user_sportivo' %}">SPORTIVI</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                {% if user.user_settings.is_prof %}
                    <li class="nav-item">
                        <a class="btn btn-sm btn-outline-success m-1 page-scroll"
                           href="{% url 'eventi_management:event-insert' %}">INSERISCI
                            EVENTO</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-sm btn-outline-success m-1 page-scroll"
                           href="{% url 'eventi_management:event-list' %}">I MIEI
                            EVENTI</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="btn btn-sm btn-outline-info m-1 page-scroll" href="{% url 'user_management:user' %}"
                       role="button">{{ user.username }}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="btn btn-sm btn-outline-success m-1 page-scroll"
                       href="{% url 'user_management:user-login' %}" role="button">LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-sm btn-outline-secondary m-1 page-scroll"
                       href="{% url 'user_management:user-register' %}" role="button">Registrati</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav> <!-- end of navbar -->

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}