DAWEY/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DAWEY.views import HomePageView, HomePageView_Seminario_User, HomePageView_User, HomePageView_Corso_User, \
    HomePageView_Competizione_User, HomePageView_Sportivo_User

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('home', HomePageView_User.as_view(), name='home_user'),
    path('home/seminario', HomePageView_Seminario_User.as_view(), name='home_user_seminario'),
    path('home/corso', HomePageView_Corso_User.as_view(), name='home_user_corso'),
    path('home/competizione', HomePageView_Competizione_User.as_view(), name='home_user_competizione'),
    path('home/sportivo', HomePageView_Sportivo_User.as_view(), name='home_user_sportivo'),
    path('user_management/', include('user_management.urls')),
    path('eventi_management/', include('eventi_management.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventi_management/urls.py
from django.urls import path

from eventi_management import views

app_name = 'eventi_management'

urlpatterns = [
    path('event/insert', views.InsertEvent.as_view(), name='event-insert'),
    path('event/insert/seminario', views.SeminarioInsert.as_view(), name='seminario-insert'),
    path('event/insert/competizione', views.CompetizioneEvent.as_view(), name='competizione-insert'),
    path('event/insert/corso', views.CorsoInsert.as_view(), name='corso-insert'),
    path('event/insert/sportivo', views.SportivoInsert.as_view(), name='sportivo-insert'),
    path('event/list', views.EventListUserCreate.as_view(), name='event-list'),
    path('event/<int:pk>', views.EventoSingolo.as_view(), name='evento-singolo'),
    path('event/user_event', views.event_user, name='event-user'),
    path('event/<int:pk>/delete', views.DeleteEvent.as_view(), name='event-delete'),
    path('event/user_delete_event', views.elimina_evento_user, name='event-delete-user'),
    path('event/<int:pk>/delete_user_evento', views.DeleteUserFromEvent.as_view(), name='event-delete-user-evento'),
    path('event/<int:pk>/seminario/update', views.SeminarioUpdate.as_view(), name='seminario-update'),
    path('event/<int:pk>/corso/update', views.CorsoUpdate.as_view(), name='corso-update'),
    path('event/<int:pk>/competizione/update', views.CompetizioneUpdate.as_view(), name='competizione-update'),
    path('event/<int:pk>/sportivo/update', views.SportivoUpdate.as_view(), name='sportivo-update'),
    path('event/<int:pk>/list_user', views.PartecipantiEvento.as_view(), name='event-list'),
]

eventi_management/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['id']


class Universita(models.Model):
    name = models.CharField(max_length=150)
    citta = models.CharField(max_length=150)

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['id']


class Corso_di_laurea(models.Model):
    name = models.CharField(max_length=150)
    universita = models.ForeignKey(Universita, on_delete=models.CASCADE)

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['id']


class Tipo_festa(models.Model):
    name = models.CharField(max_length=150)

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['id']


class Tipo_tutorato(models.Model):
    name = models.CharField(max_length=150)

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['id']


# Create your models here.
class Tags(models.Model):
    name = models.CharField(max_length=150)

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['id']


class Event(models.Model):
    user_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='user_events')  # Reference to the table User, created automatically by
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name='category_event')
    title = models.CharField(max_length=150)
    descrizione = models.CharField(max_length=15000)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField(null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    posti = models.IntegerField(null=True, blank=True)
    foto = models.ImageField(upload_to='images/', null=True, blank=True)
    luogo = models.CharField(max_length=50, null=True, blank=True)

    long = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    email_extra = models.EmailField(null=True, blank=True)
    link = models.URLField(max_length=250, null=True, blank=True)
    evento_online = models.BooleanField(default=False)

    gratuito = models.BooleanField(default=True)
    prezzo = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)

    universita = models.ForeignKey(Universita, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('home_user')

    class Meta:
        ordering = ['date_start']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Seminario(Event):
    ospite = models.CharField(max_length=250, null=True, blank=True)


class Corso(Event):
    responsabile = models.CharField(max_length=250, null=True, blank=True)


class Competizione(Event):
    responsabile = models.CharField(max_length=250, null=True, blank=True)
    sponsor = models.CharField(max_length=250, null=True, blank=True)
    n_persone_per_squadra = models.IntegerField(null=True, blank=True)
    premio = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


class Sportivo(Event):
    responsabile = models.CharField(max_length=250, null=True, blank=True)
    sport = models.CharField(max_length=250, null=True, blank=True)


class Festa(Event):
    tipo_festa = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='tipo_festa_event')
    genere_musicale = models.CharField(max_length=250, null=True, blank=True)


class Tutorato(Event):
    tipo_tutorato = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                      related_name='tipo_tutorato_event')
    materia = models.CharField(max_length=250, null=True, blank=True)
    anno = models.IntegerField(null=True, blank=True)

eventi_management/views.py
from datetime import date
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView

from DAWEY.views import BasicView
from eventi_management.forms import SeminarioInsertForm, UpdateSeminarioCrispyForm, CorsoInsertForm, \
    CompetizioneInsertForm, \
    SportivoInsertForm, UpdateCorsoCrispyForm, UpdateCompetizioneCrispyForm, UpdateSportivoCrispyForm
from eventi_management.models import Seminario, Corso, Competizione, Sportivo, Event
from user_management.models import UserAndEvent


class InsertEvent(TemplateView):
    template_name = 'inserimeto_evento/inserimento_evento_generico.html'


class SeminarioInsert(LoginRequiredMixin,CreateView):
    template_name = 'inserimeto_evento/inserimento_form.html'
    form_class = SeminarioInsertForm
    model = Seminario

    def form_valid(self, form):
        if form.is_valid():
            evento = form.save(commit=False)
            evento.user_owner = self.request.user
            evento.save()
        return super().form_valid(form)


class CompetizioneEvent(LoginRequiredMixin,CreateView):
    template_name = 'inserimeto_evento/inserimento_form.html'
    form_class = CompetizioneInsertForm
    model = Competizione

    def form_valid(self, form):
        if form.is_valid():
            evento = form.save(commit=False)
            evento.user_owner = self.request.user
            evento.save()
        return super().form_valid(form)


class CorsoInsert(LoginRequiredMixin,CreateView):
    template_name = 'inserimeto_evento/inserimento_form.html'
    form_class = CorsoInsertForm
    model = Corso

    def form_valid(self, form):
        if form.is_valid():
            evento = form.save(commit=False)
            evento.user_owner = self.request.user
            evento.save()
        return super().form_valid(form)


class SportivoInsert(LoginRequiredMixin,CreateView):
    template_name = 'inserimeto_evento/inserimento_form.html'
    form_class = SportivoInsertForm
    model = Sportivo

    def form_valid(self, form):
        if form.is_valid():
            evento = form.save(commit=False)
            evento.user_owner = self.request.user
            evento.save()
        return super().form_valid(form)


class EventListUserCreate(LoginRequiredMixin, BasicView, TemplateView):
    template_name = 'user_list_created_event.html'

    tutti = None
    seminario = None
    corso = None
    competizione = None
    sportivo = None
    grafico = None

    def get_context_data(self, **kwargs):
        context = super(EventListUserCreate, self).get_context_data(**kwargs)

        self.seminario = Seminario.objects.filter(user_owner_id=self.request.user.pk)
        self.corso = Corso.objects.filter(user_owner_id=self.request.user.pk)
        self.competizione = Competizione.objects.filter(user_owner_id=self.request.user.pk)
        self.sportivo = Sportivo.objects.filter(user_owner_id=self.request.user.pk)
        self.grafico = Event.objects.filter(user_owner_id=self.request.user.pk)
        self.tutti = chain(self.seminario, self.corso, self.competizione, self.sportivo)
        return context


class EventoSingolo(LoginRequiredMixin, BasicView, TemplateView):
    template_name = 'evento_singolo.html'
    evento = None
    creatore = None

    def get_context_data(self, **kwargs):
        context = super(EventoSingolo, self).get_context_data(**kwargs)
        self.evento = Event.objects.get(pk=self.kwargs['pk'])
        self.creatore = User.objects.get(pk=self.evento.user_owner_id)
        if self.request.user.is_authenticated:
            id_eventi_prenotati = UserAndEvent.objects.filter(user=self.request.user).values('id_event')
            self.object_eventi_prenotati = Event.objects.filter(date__gte=date.today(),
                                                                pk__in=id_eventi_prenotati)
        return context


class PartecipantiEvento(LoginRequiredMixin, BasicView, TemplateView):
    template_name = 'list_user_event.html'
    partecipanti = None

    def get_context_data(self, **kwargs):
        context = super(PartecipantiEvento, self).get_context_data(**kwargs)

        id_utenti_prenotati = UserAndEvent.objects.filter(id_event=self.kwargs['pk']).values('user')
        self.partecipanti = User.objects.filter(pk__in=id_utenti_prenotati)
        return context


class EventoUpdate(LoginRequiredMixin, BasicView, UpdateView):
    template_name = 'updateEvent.html'

    def post(self, request, *args, **kwargs):
        """Add 'Cancel' button redirect."""
        if "cancel" in request.POST:
            # url = reverse('text_management:text-list')
            url = reverse_lazy('eventi_management:event-list')
            return HttpResponseRedirect(url)
        else:
            return super(EventoUpdate, self).post(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        """Checks if user authenticated is owner of the event"""
        if request.user != self.get_object().user_owner:
            # Block requests that attempt to provide their own foo value
            return HttpResponseForbidden()
        # now process dispatch as it otherwise normally would
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('eventi_management:event-list')


class SeminarioUpdate(EventoUpdate):
    model = Seminario
    form_class = UpdateSeminarioCrispyForm


class CorsoUpdate(EventoUpdate):
    model = Corso
    form_class = UpdateCorsoCrispyForm


class CompetizioneUpdate(EventoUpdate):
    model = Competizione
    form_class = UpdateCompetizioneCrispyForm


class SportivoUpdate(EventoUpdate):
    model = Sportivo
    form_class = UpdateSportivoCrispyForm


class DeleteUserFromEvent(BasicView, DeleteView):
    model = UserAndEvent
    template_name = 'delete_user_from_event.html'
    utente = None
    success_url = reverse_lazy('eventi_management:event-list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class DeleteEvent(BasicView, DeleteView):
    model = Event
    template_name = 'event_delete.html'
    success_url = reverse_lazy('eventi_management:event-list')

    def dispatch(self, request, *args, **kwargs):
        """Checks if user authenticated is owner of the text analysis"""
        if request.user != self.get_object().user_owner:
            # Block requests that attempt to provide their own foo value
            return HttpResponseForbidden()
        # now process dispatch as it otherwise normally would
        return super().dispatch(request, *args, **kwargs)


@login_required
@require_POST
@csrf_protect
def event_user(request):
    if request.method == "POST":
        evento_prov = Event.objects.get(pk=request.POST.get('event_id'))
        user_prov = User.objects.get(pk=request.POST.get('user_id'))
        user_and_event = UserAndEvent(user=user_prov, id_event=evento_prov)
        user_and_event.save()

        data = {
            'text_saved': True
        }
        return JsonResponse(data)


@login_required
@require_POST
@csrf_protect
def elimina_evento_user(request):
    if request.method == "POST":
        UserAndEvent.objects.filter(user=request.POST.get('user_id'),
                                    id_event=request.POST.get('event_id')).delete()
        data = {
            'text_saved': True
        }
        return JsonResponse(data)

eventi_management/templates/UserAndEvent_ajax.html
{% load static %}
<script type="text/javascript">
    function ajaxUserAndEvento(user_id, evento_id, button) {
        $.ajax({
            type: 'POST',
            headers: {
                "X-CSRFToken": '{{ csrf_token }}'
            },
            url: "{% url 'eventi_management:event-user' %}",
            data: {
                'user_id': user_id,
                'event_id': evento_id,
            },
            dataType: 'json',
            beforeSend: function () {
                $.blockUI({
                    message:
                        Swal.fire({
                            title: 'Ti stai prenotando',
                            text: 'Attendi un attimo',
                            willOpen: () => {
                                Swal.showLoading()
                            }
                        })
                });
            },
            complete: function () {
                $.unblockUI();
            },
            success: function (data) {
                Swal.fire({
                    title: 'Salvataggio avvenuto con successo!',
                    text: 'Ti sei prenotato',
                    icon: 'success',
                    confirmButtonText: 'Ok'
                }).then((result) => {
                    // Reload the Page
                    location.reload();
                });
            }
        });
    }


    function ajaxDeleteUserFromEvent(user_id, evento_id) {
        $.ajax({
            type: 'POST',
            headers: {
                "X-CSRFToken": '{{ csrf_token }}'
            },
            url: "{% url 'eventi_management:event-user' %}",
            data: {
                'user_id': user_id,
                'event_id': evento_id,
            },
            dataType: 'json',
            beforeSend: function () {
                $.blockUI({
                    message:
                        Swal.fire({
                            title: 'Ti stai prenotando',
                            text: 'Attendi un attimo',
                            onBeforeOpen: () => {
                                Swal.showLoading()
                            }
                        })
                });
            },
            complete: function () {
                $.unblockUI();
            },
            success: function (data) {
                Swal.fire({
                    title: 'Salvataggio avvenuto con successo!',
                    text: 'Ti sei prenotato',
                    icon: 'success',
                    confirmButtonText: 'Ok'
                }).then((result) => {
                    // Reload the Page
                    location.reload();
                });
            }
        });
    }
</script>

eventi_management/templates/delete_user_from_event.html
{% extends 'base.html' %}#
{% load static %}

{% block title %}Eliminazione utente{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow p-4 mb-3 bg-white w-auto">
        <h1 class="font-weight-light">Eliminazione dell'utente</h1>
        <br>
        <h5>Vuoi davvero rimuovere la prenotazione ?</h5>
        <hr>

        <form method="post">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Elimina">
            <a class="btn btn-secondary" href="{% url 'eventi_management:event-list' %}">
                Annulla
            </a>
        </form>
    </div>
{% endblock %}

eventi_management/templates/eliminaEventoUserAjax.html
{% load static %}
<script type="text/javascript">
    function ajaxDeleteUserAndEvento(user_id, evento_id, button) {
        Swal.fire({
            title: 'Sei sicuro di volerti eliminare?',
            text: "Perderai la tua prenotazione",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: 'POST',
                    headers: {
                        "X-CSRFToken": '{{ csrf_token }}'
                    },
                    url: "{% url 'eventi_management:event-delete-user' %}",
                    data: {
                        'user_id': user_id,
                        'event_id': evento_id,
                    },
                    dataType: 'json',

                    success: function () {
                        Swal.fire({
                            title: 'Eliminato con successo!',
                            text: 'Ti sei eliminato',
                            icon: 'success',
                            confirmButtonText: 'Ok'
                        }).then((result) => {
                            // Reload the Page
                            location.reload();
                        });
                    }
                });
            }
        })
    }
</script>

eventi_management/templates/event_delete.html
{% extends 'base.html' %}#
{% load static %}

{% block title %}Eliminazione evento{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow p-4 mb-3 bg-white w-auto">
        <h1 class="font-weight-light">Eliminazione evento</h1>
        <br>
        <h5>Vuoi davvero cancellare l'evento?</h5>
        <hr>
        <h4>Titolo: {{ object.title }}</h4>
        {% if object.author %}
            <p>Autore: {{ object.author }}</p>
        {% endif %}
        {% if object.category %}
            <p>Categoria: {{ object.category }}</p>
        {% else %}
            <p>Nessuna categoria</p>
        {% endif %}

        <p>Descrizione: {{ object.descrizione }}</p>
        <form method="post">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Elimina">
            <a class="btn btn-secondary" href="{% url 'eventi_management:event-list' %}">
                Annulla
            </a>
        </form>
    </div>
{% endblock %}

eventi_management/templates/list_user_event.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% block title %}Partecipanti{% endblock %}

{% block content %}
    <div class="d-flex align-items-center mt-4 justify-content-between">
        <div class="content_2 container-md shadow p-3 mt-2 bg-white mt-1">
            <div class="ml-3 d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-start">
                    <h2 class="mr-2 font-weight-light">I partecipanti al tuo evento </h2>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="data-table table table-striped table-borderless table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Cognome</th>
                        <th scope="col">Email</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for utente in view.partecipanti %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ utente.first_name }}</td>
                            <td>{{ utente.last_name }}</td>
                            <td>{{ utente.email }}</td>
                            <td>
                                <a id="delete-button" class="btn btn-outline-danger" href="{% url 'eventi_management:event-delete-user-evento' utente.pk|get_id_UserEvent:pk %}">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/eventi_creati_utente.css' %}">
{% endblock %}

{% block extra_javascript %}

    {% include 'UserAndEvent_ajax.html' %}
{% endblock %}

eventi_management/templates/updateEvent.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Modifica Evento{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow p-4 mb-3 bg-white w-auto">
        <h2 class="font-weight-light">Aggiorna i dati dell'evento: {{ object.title }}</h2>
        <hr>
        {% crispy form %}
    </div>
{% endblock %}

eventi_management/templates/user_list_created_event.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% block title %}I miei testi{% endblock %}

{% block content %}
    <div class="row d-flex align-items-center justify-content-between">
        <div class="col content_2 container-md shadow p-4 m-5 pl-10 bg-white w-auto">
            <h3 class="font-weight-light mb-4">Andamento eventi in presenza</h3>
            <div id="container">
                <canvas id="line-chart"></canvas>
            </div>
            <p class="card-text"><small class="text-muted">Calcolato in base all'affluenza degli eventi </small></p>
        </div>
        <div class="col content_2 container-md shadow p-4 m-5 pl-10 bg-white w-auto">
            <h3 class="font-weight-light mb-4">Andamento eventi online</h3>
            <div id="container">
                <canvas id="line-chart_2"></canvas>
            </div>
            <p class="card-text"><small class="text-muted">Calcolato in base all'affluenza degli eventi </small></p>
        </div>
    </div>
    <div class="row">
        <div class="content_2 container-md shadow p-3 mt-2 bg-white mt-1">
            <div class="ml-3 d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-start">
                    <h2 class="mr-2 font-weight-light">I miei eventi</h2>
                </div>
            </div>
            <hr>
            <ul class="nav nav-pills nav-fill p-2 " id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-tutti-tab" data-toggle="pill" href="#pills-tutti" role="tab"
                       aria-controls="pills-tutti" aria-selected="true">Tutti</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-seminari-tab" data-toggle="pill" href="#pills-seminari" role="tab"
                       aria-controls="pills-seminari" aria-selected="false">Seminari</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-corsi-tab" data-toggle="pill" href="#pills-corsi" role="tab"
                       aria-controls="pills-corsi" aria-selected="false">Corsi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-competizioni-tab" data-toggle="pill" href="#pills-competizioni"
                       role="tab"
                       aria-controls="pills-competizioni" aria-selected="false">Competizioni</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-sportivi-tab" data-toggle="pill" href="#pills-sportivi" role="tab"
                       aria-controls="pills-sportivi" aria-selected="false">Sportivi</a>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-tutti" role="tabpanel"
                     aria-labelledby="pills-tutti-tab">
                    {% include 'template_base/list_object.html' with object_list=view.tutti %}
                </div>
                <div class="tab-pane fade" id="pills-seminari" role="tabpanel" aria-labelledby="pills-seminari-tab">
                    {% include 'template_base/list_object.html' with object_list=view.seminario %}
                </div>
                <div class="tab-pane fade" id="pills-corsi" role="tabpanel" aria-labelledby="pills-corsi-tab">
                    {% include 'template_base/list_object.html' with object_list=view.corso %}
                </div>
                <div class="tab-pane fade" id="pills-competizioni" role="tabpanel"
                     aria-labelledby="pills-competizioni-tab">
                    {% include 'template_base/list_object.html' with object_list=view.competizioni %}
                </div>
                <div class="tab-pane fade" id="pills-sportivi" role="tabpanel" aria-labelledby="pills-sportivi-tab">
                    {% include 'template_base/list_object.html' with object_list=view.sportivo %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/eventi_creati_utente.css' %}">
{% endblock %}


{% block extra_javascript %}
    {% if view.tutti %}
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script>
            var inutile = [];
            var complessita = [];

            var inutile_2 = [];
            var complessita_2 = [];

            {% for c in view.grafico %}
                {% if c.category_id == 1 %}
                    inutile.push("");
                    complessita.push({{ c|get_evento_affluenza }});
                {% endif %}
            {% endfor %}

            {% for c in view.grafico %}
                {% if c.category_id == 2 %}
                    inutile_2.push("");
                    complessita_2.push({{ c|get_evento_affluenza }});
                {% endif %}
            {% endfor %}

            var config = {
                type: 'line',
                data: {
                    labels: inutile,
                    datasets: [{
                        data: complessita,
                        borderColor: "#3e95cd",
                        fill: true
                    }]
                },
                options: {
                    responsive: true,
                    legend: {
                        display: false
                    },
                }
            };

            var config_2 = {
                type: 'line',
                data: {
                    labels: inutile_2,
                    datasets: [{
                        data: complessita_2,
                        borderColor: "#3e95cd",
                        fill: true
                    }]
                },
                options: {
                    responsive: true,
                    legend: {
                        display: false
                    },
                }
            };
            window.onload = function () {
                var ctx = document.getElementById('line-chart').getContext('2d');
                window.myPie = new Chart(ctx, config);
                var ctx_2 = document.getElementById('line-chart_2').getContext('2d');
                window.myPie = new Chart(ctx_2, config_2);
            };
        </script>
    {% endif %}
{% endblock %}